# Generated by Django 5.2.7 on 2025-10-13 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contacté')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Client')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière commande')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Nombre de commandes')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total dépensé')),
            ],
            options={
                'verbose_name': 'Lead client',
                'verbose_name_plural': 'Leads clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(help_text="URL d'accès au produit", unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence')),
                ('short_description', models.TextField(blank=True, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Laissez vide si pas de réduction', max_digits=10, null=True, verbose_name='Ancien prix')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de revient')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher en page d'accueil", verbose_name='Mise en avant')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Meilleure vente')),
                ('is_new', models.BooleanField(default=False, verbose_name='Nouveauté')),
                ('is_active', models.BooleanField(default=True, help_text='Le produit est visible sur le site', verbose_name='Actif')),
                ('in_stock', models.PositiveIntegerField(default=1, verbose_name='Quantité en stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte de stock")),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Gérer les stocks')),
                ('meta_title', models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères)', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Description SEO')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Spécifications techniques')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Caractéristiques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('available_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date à partir de laquelle le produit est disponible à la vente', verbose_name='Date de disponibilité')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category', verbose_name='Catégorie')),
                ('related_products', models.ManyToManyField(blank=True, to='app.product', verbose_name='Produits associés')),
            ],
            options={
                'verbose_name': 'Montre',
                'verbose_name_plural': 'Montres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('customer_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('customer_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Adresse de facturation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app.customerlead')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='app.product')),
            ],
            options={
                'verbose_name': 'Configuration de montre',
                'verbose_name_plural': 'Configurations de montres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customerlead',
            name='product_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
            options={
                'ordering': ['is_featured', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Très mauvais'), (2, '2 - Mauvais'), (3, '3 - Moyen'), (4, '4 - Bon'), (5, '5 - Excellent')], verbose_name='Note')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.review')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.subcategory', verbose_name='Sous-catégorie'),
        ),
    ]
