# Generated by Django 5.2.7 on 2025-10-19 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('banner_type', models.CharField(choices=[('upload', 'Téléversement de vidéo'), ('url', 'Lien vidéo')], default='upload', max_length=10, verbose_name='type de bannière')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='banners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='fichier vidéo')),
                ('video_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL de la vidéo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='banners/thumbnails/', verbose_name='image de prévisualisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
            options={
                'verbose_name': 'bannière vidéo',
                'verbose_name_plural': 'bannières vidéo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
    ]
