# Generated by Django 5.2.7 on 2025-10-19 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videobanner_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobanner',
            name='button_1_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='texte du bouton 1'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='button_1_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='lien du bouton 1'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='button_2_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='texte du bouton 2'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='button_2_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='lien du bouton 2'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="opacité de l'overlay (%)"),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='show_buttons',
            field=models.BooleanField(default=True, verbose_name='afficher les boutons'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='show_overlay',
            field=models.BooleanField(default=True, verbose_name="afficher l'overlay"),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='show_subtitle',
            field=models.BooleanField(default=True, verbose_name='afficher le sous-titre'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='afficher le titre'),
        ),
        migrations.AddField(
            model_name='videobanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='sous-titre'),
        ),
        migrations.AlterField(
            model_name='videobanner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre principal'),
        ),
    ]
