# Generated by Django 5.2.7 on 2025-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('page_type', models.CharField(choices=[('terms', "Conditions d'utilisation"), ('privacy', 'Politique de confidentialité')], max_length=20, unique=True, verbose_name='Type de page')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Page légale',
                'verbose_name_plural': 'Pages légales',
                'ordering': ['title'],
            },
        ),
    ]
